### ISSUE TITLE
Partial View

### ISSUE THREAD

**Issue by ghost** [AmigosDeJesus/Extend#18]
Existem várias interfaces no nosso sistema com nomes repetidos, para evitar isso, sugiro o uso de **Partial Views** para o reuso delas. Segue um [link](https://stackoverflow.com/questions/4287685/jsp-equivalent-of-asp-net-mvcs-partial-views) para mais informações sobre o recurso.

**Comment by Eddyosos** [comment]
Isso está especificamente relacionado com o hambúrguer menu e a barra superior.
