### ISSUE TITLE
Menu Hambúrguer II

### ISSUE THREAD

**Issue by ghost** [AmigosDeJesus/Extend#25]
Disponibilizar opções diferentes para cada página no menu hambúrguer.

**Comment by GabrielNunez** [comment]
Estimativa de finalização da melhoria: 27/06

**Comment by ghost** [comment]
https://www.w3schools.com/js/js_events.asp
https://www.w3schools.com/js/js_if_else.asp
https://www.w3schools.com/js/js_whereto.asp
