### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by ghost** [AmigosDeJesus/Extend#6]
É formada pelas funcionalidades **Temperatura**, **Alarme**, **Energia** e **Hambúrguer***.

**Comment by eliezerdejj** [comment]
Hambúrguer está feito como mostra a imagem? preciso de orientação de como fazer essas outras funcionalidades, porque elas seriam os sensores específicos, como eles deveriam ser feitos? só com imagens, ou algo deve funcionar?
![captura de tela de 2017-05-21 22-38-26](https://cloud.githubusercontent.com/assets/16067916/26289482/df123ce8-3e76-11e7-978a-b81eb54c1aef.png)

**Comment by ghost** [comment]
A intenção, no início, era de que a função Logoff fosse bem abaixo no Menu, mas acho q assim não tem problema. No caso da tela dos sensores, acredito q esteja com outra pessoa. O trabalho requer q apenas uma função entre muitas funcione, salvo engano foi definido q apenas a função "Adicionar Sensor" seria implementada, mas não tenho certeza.

**Comment by eliezerdejj** [comment]
Entendi, no caso, se ela for implementada os sensores cadastrados devem aparecer na tela inicial(index)

**Comment by ghost** [comment]
Exatamente, junto com **Temperatura**, **Alarme** e **Energia**.
